# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andrew Galassi
email: andrewgalassi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Robotics Technologist at NASA JPL. Multi-robot systems for planetary exploration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.andrewgalassi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: andrewgalassi

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

scholar:
  style: ieee-asl
  bibliography: Federico.bib
  sort_by: year
  order: descending
  group_by: type
  type_order: [article,inproceedings,techreport,thesis]
  type_aliases: {Incollection: techreport}
  type_names: { unpublished: Manuscripts}
  bibliography_template: bib
  reference_tagname: span class="entry"
  bibliography_group_tag: 'h3'
